### ISSUE TITLE
DNS Migration - learn.eosnetwork.com

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/engineering#59]
We want to change servers for the learn portal on `learn.eosnetwork.com`. 
In order to do so, we need to point the DNS to the hosted zone.

I've forwarded the information to @kj4ezj in a private message, this ticket is merely for tracking purposes.

## See Also
- engineering [issue 54](https://github.com/eosnetworkfoundation/engineering/issues/54) - Point DNS to `ide.eosnetwork.com`
- engineering [issue 55](https://github.com/eosnetworkfoundation/engineering/issues/55) - DNS Migration - `docs.eosnetwork.com`
- engineering [issue 56](https://github.com/eosnetworkfoundation/engineering/issues/56) - Tear Down Old Documentation Infrastructure

**Comment by kj4ezj** [comment]
ENF Automation, in collaboration with Engineering, intentionally excluded `learn.eosnetwork.com` from the migration of Developer Relations cloud infrastructure in [issue 54](https://github.com/eosnetworkfoundation/engineering/issues/54), [issue 55](https://github.com/eosnetworkfoundation/engineering/issues/55), and [issue 56](https://github.com/eosnetworkfoundation/engineering/issues/56) because the DevHub "learn portal" system was built out using modern tooling and Amazon Web Services (AWS) best-practices.

### Web Hosting
Automation estimates that, based on cloud costs and website usage figures, the proposed migration destination infrastructure will cost the same amount of money as one year of the existing web hosting infrastructure in just the first 145 hours. The existing web hosting infrastructure already has a self-service CICD deployment ([`frontend.yml`](https://github.com/eosnetworkfoundation/devhub/blob/v1.0.8/.github/workflows/frontend.yml#L65), [`frontend-publish.sh`](https://github.com/eosnetworkfoundation/devhub/blob/v1.0.8/.github/workflows/frontend-publish.sh)) that is [actively being used](https://github.com/eosnetworkfoundation/devhub/actions/runs/5134363890) to great affect. For these reasons, Automation and Engineering recommend _against_ any web hosting migrations.

### Database
The database hosting represents 99.98% of the cost of the DevHub "learn portal" due to the [`m6a.2xlarge` instance type](https://instances.vantage.sh/aws/ec2/m6a.2xlarge) requested by Developer Relations to host [Couchbase](https://en.wikipedia.org/wiki/Couchbase_Server). This request was not arbitrary on DevRel's part, it was based on [Couchbase hardware requirements](https://docs.couchbase.com/server/current/install/pre-install.html). Automation has identified this as the greatest cost factor and recommends reducing this cost by using a managed database provider, such as [DocumentDB](https://aws.amazon.com/documentdb), as @tedcahalleos initially recommended.

[Firebase](https://en.wikipedia.org/wiki/Firebase) is a managed database provider identified by Developer Relations that would address these cost concerns, but Automation recommends against this tool due to [privacy issues](https://en.wikipedia.org/wiki/Firebase#User_privacy_controversies) that could put our community at risk.

## Recommendations
Automation recommends that, instead of any DNS migration, the ENF elevate Developer Relations IAM user permissions in the `devhub` AWS account such that they can manage all of the infrastructure in a self-service manner, if they cannot already. Such an escalation will not preclude the use of Firebase or any of the other intended implementation details shared via IM. Finally, Automation recommends the use of a managed database provider that respects user privacy.

**Comment by nsjames** [comment]
The change will lower costs by a factor of 10 instantly. Everything is already set up on the new server.

You can elevate my IAM there, I'll handle tearing everything down and pointing the DNS.

**Comment by kj4ezj** [comment]
Leadership directed Automation to close this ticket as stale because we have not heard from the customer in 35 days, so this work must not be important.
